country_name: "libya"
ssp_input_file_name: "sisepuede_raw_inputs_latest_LBY_modified_march_2026.csv"
ssp_transformation_cw: "ssp_libya_transformation_cw_20260310.xlsx"
set_lndu_reallocation_factor_to_zero: true
energy_model_flag: true
sim_end_year: 2050